### ISSUE TITLE
“forward() takes from 2 to 4 positional arguments but 7 were given”

### ISSUE THREAD

**Issue by zhihao-chen** [wjunneng/2020-AI-Financial-User-Review-Categories#1]
您好，您的原始model架构我没有更改，只改了dataloader。然后运行出现这个问题“forward() takes from 2 to 4 positional arguments but 7 were given”。希望能得到您的帮助，谢谢
![截屏2020-07-22 上午11 53 50](https://user-images.githubusercontent.com/33823337/88132541-5d98e400-cc12-11ea-8418-2ffca4da87bc.png)

**Comment by wjunneng** [comment]
您好，实在抱歉刚看到，可能的原因是 transformers==2.11.0 的缘故，各种依赖包可以参考requirements.txt文件，希望对您有帮助。

**Comment by wjunneng** [comment]
> 您好，您的原始model架构我没有更改，只改了dataloader。然后运行出现这个问题“forward() takes from 2 to 4 positional arguments but 7 were given”。希望能得到您的帮助，谢谢
> ![截屏2020-07-22 上午11 53 50](https://user-images.githubusercontent.com/33823337/88132541-5d98e400-cc12-11ea-8418-2ffca4da87bc.png)

您好，实在抱歉刚看到，可能的原因是 transformers==2.1.1 的缘故，各种依赖包可以参考requirements.txt文件，希望对您有帮助。
